DROP SEQUENCE CLIENTE_SEQ;

DROP SEQUENCE PAGO_SEQ;

DROP SEQUENCE SINIESTRO_SEQ;

DROP TABLE CLIENTE CASCADE CONSTRAINTS;

DROP TABLE COTIZACIONES CASCADE CONSTRAINTS;

DROP VIEW V_COTIZACIONES;

TRUNCATE TABLE TABULAR;

DROP TABLE TABULAR;

DROP TABLE PAGO CASCADE CONSTRAINTS;

DROP TABLE POLIZA CASCADE CONSTRAINTS;

DROP TABLE SINIESTRO CASCADE CONSTRAINTS;

DROP TABLE SINIESTRO_COLISION CASCADE CONSTRAINTS;

DROP TABLE SINIESTRO_SOCIAL CASCADE CONSTRAINTS;

DROP TABLE SINIESTRO_MATERIAL CASCADE CONSTRAINTS;

DROP TABLE ESTADOS_REPUBLICA_MEXICANA CASCADE CONSTRAINTS;

DROP TABLE AUTOS CASCADE CONSTRAINTS;

DROP TABLE MARCA_AUTOS CASCADE CONSTRAINTS;

DROP TABLE MODELO_AUTOS CASCADE CONSTRAINTS;

DROP TABLE TIPO_SEGUROS CASCADE CONSTRAINTS;