-- 
-- CATALOGO: ESTADOS
--
CREATE TABLE ESTADOS_REPUBLICA_MEXICANA(
    CLAVE_ESTADO    VARCHAR2(5)     NOT NULL,
    NOMBRE_ESTADO   VARCHAR2(25)    NOT NULL UNIQUE,
    CONSTRAINT PK106 PRIMARY KEY (CLAVE_ESTADO)
);

-- 
-- CATALOGO: MARCA AUTOS
--
CREATE TABLE MARCA_AUTOS(
    CLAVE_MARCA    VARCHAR2(10)     NOT NULL,
    MARCA          VARCHAR2(20)     NOT NULL UNIQUE,
    CONSTRAINT PK108 PRIMARY KEY (CLAVE_MARCA)
);

-- 
-- CATALOGO: MODELOS AUTOS
--
CREATE TABLE MODELO_AUTOS(
    CLAVE_MODELO    VARCHAR2(10)       NOT NULL,
    MARCA_MODELO    VARCHAR2(25)       NOT NULL,
    NOMBRE_MODELO   VARCHAR2(25)       NOT NULL UNIQUE,
    CONSTRAINT PK109 PRIMARY KEY (CLAVE_MODELO)
);

-- 
-- CATALOGO: TIPO SEGUROS
--
CREATE TABLE TIPO_SEGUROS(
    CLAVE_SEGURO    VARCHAR2(5)     NOT NULL,
    NOMBRE_SEGURO   VARCHAR2(25)    NOT NULL,
    CONSTRAINT PK110 PRIMARY KEY (CLAVE_SEGURO)
);

-- 
-- TABLE: CLIENTE
--
CREATE TABLE CLIENTE(
    CLIENTE_ID    NUMBER(2, 0)    NOT NULL,
    NOMBRE        VARCHAR2(15)    NOT NULL,
    AP_PATERNO    VARCHAR2(15)    NOT NULL,
    AP_MATERNO    VARCHAR2(15)    NULL,
    RFC           VARCHAR2(15)    NULL,
    EMAIL         VARCHAR2(25)    NOT NULL,
    TELEFONO      NUMBER(10, 0)   NOT NULL,
    DIRECCION     VARCHAR(50)     NULL,
    CONSTRAINT PK101 PRIMARY KEY (CLIENTE_ID)
);

-- 
-- TABLE: COTIZACIONES
--
CREATE TABLE COTIZACIONES(
    CLIENTE_ID             NUMBER(2, 0)    NOT NULL,
    COTIZACIONES_ID        NUMBER(2, 0)    NOT NULL,
    COTIZACIONES_NUM       NUMBER(4, 0)    NOT NULL,
    FECHA_COTIZACION       DATE            NOT NULL,
    TIPO_SEGURO            VARCHAR2(2)     NOT NULL,
    CLAVE_MARCA            VARCHAR2(10)    NOT NULL,
    CLAVE_MODELO           VARCHAR2(10)    NOT NULL,
    AÑO                    NUMBER(4, 0)    NOT NULL,
    CODIGO_POSTAL          NUMBER(8, 0)    NOT NULL,
    CLAVE_ESTADO           VARCHAR2(5)     NOT NULL,
    FECHA_NAC              DATE            NOT NULL,
    CONSTRAINT PK102 PRIMARY KEY (COTIZACIONES_ID),
    CONSTRAINT RefCLIENTE2 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefCESTADO2 FOREIGN KEY (CLAVE_ESTADO)
    REFERENCES ESTADOS_REPUBLICA_MEXICANA(CLAVE_ESTADO),
    CONSTRAINT RefAMARCA2 FOREIGN KEY (CLAVE_MARCA)
    REFERENCES MARCA_AUTOS(CLAVE_MARCA),
    CONSTRAINT RefAMODELO2 FOREIGN KEY (CLAVE_MODELO)
    REFERENCES MODELO_AUTOS(CLAVE_MODELO)
);

CREATE OR REPLACE VIEW V_COTIZACIONES AS
SELECT CLIENTE_ID, COTIZACIONES_ID, COTIZACIONES_NUM, FECHA_COTIZACION, TIPO_SEGURO, CLAVE_MARCA, CLAVE_MODELO, AÑO, CODIGO_POSTAL, CLAVE_ESTADO, FECHA_NAC, ((SYSDATE - FECHA_NAC)/365.25) EDAD
FROM COTIZACIONES;

-- 
-- TABLE: PAGO
--
CREATE TABLE PAGO(
    PAGO_ID              NUMBER(2, 0)     NOT NULL,
    CLIENTE_ID           NUMBER(2, 0)     NOT NULL,
    NUMERO_TARJETA       VARCHAR2(16)     NOT NULL,
    CONSTRAINT CHK_NUM_TARK UNIQUE (NUMERO_TARJETA),
    TIPO                 VARCHAR2(10)     DEFAULT 'DEBITO',
    CONSTRAINT CHK_TIPO CHECK (TIPO = 'DEBITO'),
    MES_VENCIMIENTO      NUMBER(2, 0)     NOT NULL,
    AÑO_VENCIMIENTO      NUMBER(4, 0)     NOT NULL,
    CONSTRAINT CHK_AÑO CHECK (AÑO_VENCIMIENTO > 2018),
    NUMERO_SEGURIDAD     NUMBER(3, 0)     NOT NULL,
    COSTO                NUMBER(7, 0)     NOT NULL,
    CONSTRAINT PK103 PRIMARY KEY (PAGO_ID),
    CONSTRAINT RefCLIENTE4 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
);

-- 
-- TABLE: POLIZA
-- 
CREATE TABLE POLIZA(
    PAGO_ID                        NUMBER(2, 0)     NOT NULL,
    CLIENTE_ID                     NUMBER(2, 0)     NOT NULL,
    POLIZA_ID                      NUMBER(2, 0)     NOT NULL,
    POLIZA_ANTERIOR_ID             NUMBER(2, 0)     NULL,
    SINIESTRO_ID                   NUMBER(2, 0)     DEFAULT 0,
    SINIESTRO_NUM                  NUMBER(2, 0)     NULL,
    CONSTRAINT CHK_SINIESTRO CHECK (SINIESTRO_NUM < 11),
    COTIZACIONES_ID                NUMBER(2, 0)     NOT NULL,
    FOLIO                          VARCHAR2(13)     NOT NULL,
    HORA_INICIO                    DATE             NOT NULL,
    FECHA_INICIO                   DATE             NOT NULL,
    FECHA_FIN                      DATE             NOT NULL,
    NUM_PLACAS                     NUMBER(5, 0)     NOT NULL,
    NUM_SERIE                      NUMBER(17, 0)    NOT NULL,
    CONSTRAINT CHK_SERIE UNIQUE (NUM_SERIE),
    CONSTRAINT PK104 PRIMARY KEY (POLIZA_ID),
    CONSTRAINT RefCLIENTE5 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefPAGO2 FOREIGN KEY (PAGO_ID)
    REFERENCES PAGO(PAGO_ID),
    CONSTRAINT RefRENOVACION FOREIGN KEY (POLIZA_ANTERIOR_ID)
    REFERENCES POLIZA(POLIZA_ID),
    CONSTRAINT RefCOTIZACIONES7 FOREIGN KEY (COTIZACIONES_ID)
    REFERENCES COTIZACIONES(COTIZACIONES_ID)
);

-- 
-- TABLE: SINIESTRO
--
CREATE TABLE SINIESTRO(
    CLIENTE_ID              NUMBER(2, 0)     NOT NULL,
    SINIESTRO_ID            NUMBER(2, 0)     NOT NULL,
    POLIZA_ID               NUMBER(2, 0)     NOT NULL,
    CATEGORIA_SINIESTRO     VARCHAR2(10)     NOT NULL,
    HORA_Y_FECHA            DATE             NOT NULL,
    DIRECCION               VARCHAR2(50)     NOT NULL,
    DESCRIPCION             VARCHAR2(70)     NOT NULL,
    FOTO_ACCIDENTE          BLOB             NULL,
    CONSTRAINT PK105 PRIMARY KEY (SINIESTRO_ID),
    CONSTRAINT RefCLIENTE6 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefPOLIZA2 FOREIGN KEY (POLIZA_ID)
    REFERENCES POLIZA(POLIZA_ID)      
);

-- 
-- TABLE: SINIESTRO_COLISION
--
CREATE TABLE SINIESTRO_COLISION(
    CLIENTE_ID               NUMBER(2, 0)   NOT NULL,
    SINIESTRO_ID             NUMBER(2, 0)   NOT NULL,
    POLIZA_ID                NUMBER(2, 0)   NOT NULL,
    NUMERO_REPORTE_VIAL      VARCHAR2(8)    NOT NULL,
    GRUA                     NUMBER(1, 0)   NOT NULL,
    MARCA_ASEGURADO1         VARCHAR2(10)   NOT NULL,
    MODELO_ASEGURADO1        VARCHAR2(10)   NOT NULL,
    MARCA_AFECTADO1          VARCHAR2(10)   NOT NULL,
    MODELO_AFECTADO1         VARCHAR2(10)   NOT NULL,
    ASEGURADORA_AFECTADO1    VARCHAR2(8)    NOT NULL,
    POLIZA_AFECTADO1         VARCHAR(20)    NOT NULL,
    AGENCIA_AFECTADO1        VARCHAR(20)    NOT NULL,
    MARCA_AFECTADO2          VARCHAR2(10)   NULL,
    MODELO_AFECTADO2         VARCHAR2(10)   NULL,
    ASEGURADORA_AFECTADO2    VARCHAR2(8)    NULL,
    POLIZA_AFECTADO2         VARCHAR(20)    NULL,
    AGENCIA_AFECTADO2        VARCHAR(20)    NULL,
    MARCA_AFECTADO3          VARCHAR2(10)   NULL,
    MODELO_AFECTADO3         VARCHAR2(10)   NULL,
    ASEGURADORA_AFECTADO3    VARCHAR2(8)    NULL,
    POLIZA_AFECTADO3         VARCHAR(20)    NULL,
    AGENCIA_AFECTADO3        VARCHAR(20)    NULL,
    MARCA_AFECTADO4          VARCHAR2(10)   NULL,
    MODELO_AFECTADO4         VARCHAR2(10)   NULL,
    ASEGURADORA_AFECTADO4    VARCHAR2(8)    NULL,
    POLIZA_AFECTADO4         VARCHAR(20)    NULL,
    AGENCIA_AFECTADO4        VARCHAR(20)    NULL,
    CONSTRAINT RefCLIENTE7 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefSINIESTRO2 FOREIGN KEY (SINIESTRO_ID)
    REFERENCES SINIESTRO(SINIESTRO_ID)
);

-- 
-- TABLE: SINIESTRO_SOCIAL
--
CREATE TABLE SINIESTRO_SOCIAL(
    CLIENTE_ID              NUMBER(2, 0)    NOT NULL,
    SINIESTRO_ID            NUMBER(2, 0)    NOT NULL,
    POLIZA_ID               NUMBER(10)      NOT NULL,
    AMBULANCIA              NUMBER(1, 0)    NOT NULL,
    HOSPITAL                VARCHAR2(25)    NOT NULL,
    NOMBRE_AFECTADO1        VARCHAR2(25)    NULL,
    AP_PATERNO_AFECTADO1    VARCHAR2(25)    NULL,
    AP_MATERNO_AFECTADO1    VARCHAR2(25)    NULL,
    CURP_AFECTADO1          VARCHAR2(20)    NULL,
    DANO_AFECTADO1          VARCHAR2(50)    NULL,
    NOMBRE_AFECTADO2        VARCHAR2(25)    NULL,
    AP_PATERNO_AFECTADO2    VARCHAR2(25)    NULL,
    AP_MATERNO_AFECTADO2    VARCHAR2(25)    NULL,
    CURP_AFECTADO2          VARCHAR2(20)    NULL,
    DANO_AFECTADO2          VARCHAR2(50)    NULL,
    NOMBRE_AFECTADO3        VARCHAR2(25)    NULL,
    AP_PATERNO_AFECTADO3    VARCHAR2(25)    NULL,
    AP_MATERNO_AFECTADO3    VARCHAR2(25)    NULL,
    CURP_AFECTADO3          VARCHAR2(20)    NULL,
    DANO_AFECTADO3          VARCHAR2(50)    NULL,
    NOMBRE_AFECTADO4        VARCHAR2(25)    NULL,
    AP_PATERNO_AFECTADO4    VARCHAR2(25)    NULL,
    AP_MATERNO_AFECTADO4    VARCHAR2(25)    NULL,
    CURP_AFECTADO4          VARCHAR2(20)    NULL,
    DANO_AFECTADO4          VARCHAR2(50)    NULL,
    NOMBRE_AFECTADO5        VARCHAR2(25)    NULL,
    AP_PATERNO_AFECTADO5    VARCHAR2(25)    NULL,
    AP_MATERNO_AFECTADO5    VARCHAR2(25)    NULL,
    CURP_AFECTADO5          VARCHAR2(20)    NULL,
    DANO_AFECTADO5          VARCHAR2(50)    NULL,
    CONSTRAINT RefCLIENTE8 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefSINIESTRO3 FOREIGN KEY (SINIESTRO_ID)
    REFERENCES SINIESTRO(SINIESTRO_ID)
);

-- 
-- TABLE: SINIESTRO_MATERIAL
--
CREATE TABLE SINIESTRO_MATERIAL(
    CLIENTE_ID              NUMBER(2, 0)     NOT NULL,
    SINIESTRO_ID            NUMBER(2, 0)     NOT NULL,
    POLIZA_ID               NUMBER(10)       NOT NULL,
    DIRECCION               VARCHAR2(50)     NOT NULL,
    DESCRIPCION             VARCHAR2(70)     NOT NULL,
    FOTO_ACCIDENTE          BLOB             NULL,
    CONSTRAINT RefCLIENTE9 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefSINIESTRO4 FOREIGN KEY (SINIESTRO_ID)
    REFERENCES SINIESTRO(SINIESTRO_ID)  
);

--ALTER TABLE POLIZA
--ADD CONSTRAINT RefSINIESTRO5 FOREIGN KEY (SINIESTRO_ID) REFERENCES SINIESTRO (SINIESTRO_ID);