SELECT NOMBRE FROM CLIENTE WHERE AP_PATERNO = 'PEREZ' OR AP_MATERNO = 'PEREZ';

SELECT CLAVE_MARCA, CLAVE_MODELO FROM V_COTIZACIONES WHERE EDAD > 20;

SELECT NOMBRE FROM CLIENTE INNER JOIN POLIZA ON CLIENTE.CLIENTE_ID = POLIZA.CLIENTE_ID WHERE SINIESTRO_ID = 0;

SELECT CLIENTE.NOMBRE, CLIENTE.AP_PATERNO SINIESTRO.DIRECCION FROM CLIENTE INNER JOIN SINIESTRO ON CLIENTE.CLIENTE_ID = SINIESTRO.CLIENTE_ID;

SELECT COSTO, COUNT(COSTO) AS NUM_COSTOS FROM (SELECT * FROM TABULAR) GROUP BY COSTO;

SELECT NOMBRE FROM CLIENTE WHERE CLIENTE_ID = 1 UNION SELECT NUMERO_TARJETA FROM PAGO WHERE CLIENTE_ID = 1;

SELECT * FROM CLIENTE CROSS JOIN POLIZA;

SELECT * FROM MARCA_AUTOS NATURAL JOIN V_COTIZACIONES WHERE CLAVE_MARCA = 'NI';

SELECT CLIENTE.NOMBRE, SINIESTRO.CATEGORIA_SINIESTRO FROM (CLIENTE INNER JOIN SINIESTRO ON CLIENTE.CLIENTE_ID = SINIESTRO.CLIENTE_ID) WHERE CLIENTE.NOMBRE = 'RAUL';

SELECT GRUA, COUNT(GRUA) AS NUM_CASOS_GRUA FROM (SELECT * FROM SINIESTRO_COLISION) GROUP BY GRUA;